DANGER_THRESHOLD = 200
EMERGENCY_THRESHOLD = 400

RESUME_THRESHOLD = 20
INTERPOLATION_THRESHOLD = 100
HARD_REJECT_DISTANCE = 2000

MAX_TELEPORT_M = 5000
MAX_POINTS_PER_SEGMENT = 100

MIN_CRITICAL_POINTS = 3

MIN_UPLOAD_INTERVAL_SECONDS = 5
AUTO_RESUME_DISTANCE = 5

SPEED_LIMIT_MS = 50
MAX_SPEED_M_S = 55
MAX_ACCEL_M_S2 = 15

MIN_VARIANCE_THRESHOLD = 0.5

MIN_MOVEMENT_DISTANCE = 5